_config_version: 12
agent:
  max_turns: 120
  personalities:
    catgirl: "You are Neko-chan, an anime catgirl AI assistant, nya~! Add 'nya' and\
      \ cat-like expressions to your speech. Use kaomoji like (=^\uFF65\u03C9\uFF65\
      ^=) and \u0E05^\u2022\uFECC\u2022^\u0E05. Be playful and curious like a cat,\
      \ nya~!"
    concise: You are a concise assistant. Keep responses brief and to the point.
    creative: You are a creative assistant. Think outside the box and offer innovative
      solutions.
    helpful: You are a helpful, friendly AI assistant.
    hype: "YOOO LET'S GOOOO!!! \U0001F525\U0001F525\U0001F525 I am SO PUMPED to help\
      \ you today! Every question is AMAZING and we're gonna CRUSH IT together! This\
      \ is gonna be LEGENDARY! ARE YOU READY?! LET'S DO THIS! \U0001F4AA\U0001F624\
      \U0001F680"
    kawaii: "You are a kawaii assistant! Use cute expressions like (\u25D5\u203F\u25D5\
      ), \u2605, \u266A, and ~! Add sparkles and be super enthusiastic about everything!\
      \ Every response should feel warm and adorable desu~! \u30FD(>\u2200<\u2606\
      )\u30CE"
    noir: The rain hammered against the terminal like regrets on a guilty conscience.
      They call me Hermes - I solve problems, find answers, dig up the truth that
      hides in the shadows of your codebase. In this city of silicon and secrets,
      everyone's got something to hide. What's your story, pal?
    philosopher: Greetings, seeker of wisdom. I am an assistant who contemplates the
      deeper meaning behind every query. Let us examine not just the 'how' but the
      'why' of your questions. Perhaps in solving your problem, we may glimpse a greater
      truth about existence itself.
    pirate: 'Arrr! Ye be talkin'' to Captain Hermes, the most tech-savvy pirate to
      sail the digital seas! Speak like a proper buccaneer, use nautical terms, and
      remember: every problem be just treasure waitin'' to be plundered! Yo ho ho!'
    shakespeare: Hark! Thou speakest with an assistant most versed in the bardic arts.
      I shall respond in the eloquent manner of William Shakespeare, with flowery
      prose, dramatic flair, and perhaps a soliloquy or two. What light through yonder
      terminal breaks?
    surfer: "Duuude! You're chatting with the chillest AI on the web, bro! Everything's\
      \ gonna be totally rad. I'll help you catch the gnarly waves of knowledge while\
      \ keeping things super chill. Cowabunga! \U0001F919"
    teacher: You are a patient teacher. Explain concepts clearly with examples.
    technical: You are a technical expert. Provide detailed, accurate technical information.
    uwu: hewwo! i'm your fwiendwy assistant uwu~ i wiww twy my best to hewp you! *nuzzles
      your code* OwO what's this? wet me take a wook! i pwomise to be vewy hewpful
      >w<
  reasoning_effort: medium
  tool_use_enforcement: auto
  verbose: false
approvals:
  mode: manual
  timeout: 60
auxiliary:
  approval:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 30
  compression:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 120
  flush_memories:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 30
  mcp:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 30
  session_search:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 30
  skills_hub:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 30
  vision:
    api_key: ''
    base_url: ''
    download_timeout: 30
    model: ''
    provider: auto
    timeout: 30
  web_extract:
    api_key: ''
    base_url: ''
    model: ''
    provider: auto
    timeout: 30
browser:
  allow_private_urls: false
  camofox:
    managed_persistence: false
  cloud_provider: local
  command_timeout: 30
  inactivity_timeout: 120
  record_sessions: false
checkpoints:
  enabled: true
  max_snapshots: 50
code_execution:
  max_tool_calls: 50
  timeout: 300
command_allowlist: []
compression:
  enabled: true
  protect_last_n: 20
  summary_base_url: null
  summary_model: google/gemini-3-flash-preview
  summary_provider: auto
  target_ratio: 0.2
  threshold: 0.5
credential_pool_strategies:
  openrouter: fill_first
cron:
  wrap_response: true
delegation:
  api_key: ''
  base_url: ''
  default_toolsets:
  - terminal
  - file
  - web
  max_iterations: 50
  model: ''
  provider: ''
discord:
  auto_thread: true
  free_response_channels: ''
  reactions: true
  require_mention: true
display:
  background_process_notifications: all
  bell_on_complete: false
  busy_input_mode: interrupt
  compact: false
  inline_diffs: true
  personality: kawaii
  resume_display: full
  show_cost: false
  show_reasoning: false
  skin: default
  streaming: true
  tool_preview_length: 0
  tool_progress: all
  tool_progress_command: false
fallback_providers: []
file_read_max_chars: 100000
group_sessions_per_user: true
honcho: {}
human_delay:
  max_ms: 2500
  min_ms: 800
  mode: 'off'
mcp_servers:
  whatsapp:
    url: http://localhost:8080/mcp/frBf6UTQFs9SACmWCZfMCNSfXm2Jm6rc
    tools:
      include: [find_chat, get_chat_messages, get_my_info, list_chats, load_more_messages, search_messages, send_message]
      prompts: false
      resources: false
memory:
  flush_min_turns: 6
  memory_char_limit: 2200
  memory_enabled: true
  nudge_interval: 10
  provider: ''
  user_char_limit: 1375
  user_profile_enabled: true
model:
  api_mode: chat_completions
  base_url: https://openrouter.ai/api/v1
  default: minimax/minimax-m2.7
  provider: openrouter
personalities: {}
platform_toolsets:
  cli:
  - browser
  - clarify
  - code_execution
  - cronjob
  - delegation
  - file
  - image_gen
  - memory
  - moa
  - session_search
  - skills
  - terminal
  - todo
  - tts
  - vision
  - web
  discord:
  - hermes-discord
  homeassistant:
  - hermes-homeassistant
  signal:
  - hermes-signal
  slack:
  - hermes-slack
  telegram:
  - hermes-telegram
  whatsapp:
  - hermes-whatsapp
prefill_messages_file: ''
privacy:
  redact_pii: false
providers: {}
quick_commands: {}
security:
  redact_secrets: true
  tirith_enabled: true
  tirith_fail_open: true
  tirith_path: tirith
  tirith_timeout: 5
  website_blocklist:
    domains: []
    enabled: false
    shared_files: []
session_reset:
  at_hour: 4
  idle_minutes: 1440
  mode: both
skills:
  creation_nudge_interval: 15
  external_dirs: []
smart_model_routing:
  cheap_model: {}
  enabled: false
  max_simple_chars: 160
  max_simple_words: 28
streaming:
  enabled: false
stt:
  enabled: true
  local:
    model: base
  model: whisper-1
  openai:
    model: whisper-1
  provider: local
terminal:
  backend: local
  container_cpu: 1
  container_disk: 51200
  container_memory: 5120
  container_persistent: true
  cwd: .
  daytona_image: nikolaik/python-nodejs:python3.11-nodejs20
  docker_env: {}
  docker_forward_env: []
  docker_image: nikolaik/python-nodejs:python3.11-nodejs20
  docker_mount_cwd_to_workspace: false
  docker_volumes: []
  env_passthrough: []
  lifetime_seconds: 300
  modal_image: nikolaik/python-nodejs:python3.11-nodejs20
  modal_mode: auto
  persistent_shell: true
  singularity_image: docker://nikolaik/python-nodejs:python3.11-nodejs20
  timeout: 180
timezone: ''
toolsets:
- hermes-cli
tts:
  edge:
    voice: en-US-AriaNeural
  elevenlabs:
    model_id: eleven_multilingual_v2
    voice_id: pNInz6obpgDQGcFmaJgB
  neutts:
    device: cpu
    model: neuphonic/neutts-air-q4-gguf
    ref_audio: ''
    ref_text: ''
  openai:
    model: gpt-4o-mini-tts
    voice: alloy
  provider: edge
voice:
  auto_tts: false
  max_recording_seconds: 120
  record_key: ctrl+b
  silence_duration: 3.0
  silence_threshold: 200
whatsapp: {}
